export const Crud = {
	GET_AGENTS: 'GET_AGENTS',
	GET_INTERVIEWS: 'GET_INTERVIEWS',
	GET_ROLES: 'GET_ROLES',
	GET_OFFERS: 'GET_OFFERS'
}

export const Common = {
	START_EDITING: 'START_EDITING',
	CANCEL_EDITING: 'CANCEL_EDITING',
}