export default {
	GET_REQUEST: 'WebServiceTypes.GET_REQUEST',
	POST_REQUEST: 'WebServiceTypes.POST_REQUEST',
	PUT_REQUEST: 'WebServiceTypes.PUT_REQUEST',
	DELETE_REQUEST: 'WebServiceTypes.DELETE_REQUEST',
	ON_GET_REQUEST_SUCCESS: 'WebServiceTypes.ON_GET_REQUEST_SUCCESS',	
	ON_POST_REQUEST_SUCCESS: 'WebServiceTypes.ON_POST_REQUEST_SUCCESS',	
	ON_PUT_REQUEST_SUCCESS: 'WebServiceTypes.ON_PUT_REQUEST_SUCCESS',	
	ON_DELETE_REQUEST_SUCCESS: 'WebServiceTypes.ON_DELETE_REQUEST_SUCCESS',	
	ON_REQUEST_FAILURE: 'WebServiceTypes.ON_REQUEST_FAILURE'
}