export default {
	GET_REQUEST: 'WebServiceTypes.GET_REQUEST',
	POST_REQUEST: 'WebServiceTypes.POST_REQUEST',
	PUT_REQUEST: 'WebServiceTypes.PUT_REQUEST',
	DELETE_REQUEST: 'WebServiceTypes.DELETE_REQUEST',
	ON_REQUEST_SUCCESS: 'WebServiceTypes.ON_REQUEST_SUCCESS',	
	ON_REQUEST_FAILURE: 'WebServiceTypes.ON_REQUEST_FAILURE'
}