export default {
	// Request types
	ON_ONE_AGENT_REQUEST: 'WebServiceTypes.ON_ONE_AGENT_REQUEST',
	ON_ALL_AGENT_REQUEST: 'WebServiceTypes.ON_ALL_AGENT_REQUEST',
	ON_ONE_ROLE_REQUEST: 'WebServiceTypes.ON_ONE_ROLE_REQUEST',
	ON_ALL_ROLE_REQUEST: 'WebServiceTypes.ON_ALL_ROLE_REQUEST',
	ON_ONE_INTERVIEW_REQUEST: 'WebServiceTypes.ON_ONE_INTERVIEW_REQUEST',
	ON_ALL_INTERVIEW_REQUEST: 'WebServiceTypes.ON_ALL_INTERVIEW_REQUEST',
	// Response types
	ON_ONE_AGENT_REQUEST_SUCCESS: 'WebServiceTypes.ON_ONE_AGENT_REQUEST_SUCCESS',
	ON_ALL_AGENT_REQUEST_FAILURE: 'WebServiceTypes.ON_ALL_AGENT_REQUEST_FAILURE',
	ON_ONE_ROLE_REQUEST_SUCCESS: 'WebServiceTypes.ON_ONE_ROLE_REQUEST_SUCCESS',
	ON_ALL_ROLE_REQUEST_FAILURE: 'WebServiceTypes.ON_ALL_ROLE_REQUEST_FAILURE',
	ON_ONE_INTERVIEW_REQUEST_SUCCESS: 'WebServiceTypes.ON_ONE_INTERVIEW_REQUEST_SUCCESS',
	ON_ALL_INTERVIEW_REQUEST_FAILURE: 'WebServiceTypes.ON_ALL_INTERVIEW_REQUEST_FAILURE',
}